project_id = "imhpaotnlqnpzldeudaq"

[functions.match-providers]
verify_jwt = false

[functions.parse-request]
verify_jwt = false

[functions.simulate-bids]
verify_jwt = false

[functions.seed-providers]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.invite-staff]
verify_jwt = false
